# Generated by Django 4.0.5 on 2022-06-14 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RegionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UsersInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('introduction', models.TextField()),
                ('company', models.CharField(max_length=20)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True)),
                ('research', models.CharField(max_length=100)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reviewsite.position')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reviewsite.regiontype')),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reviewsite.sex')),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reviewsite.usertype')),
            ],
        ),
        migrations.CreateModel(
            name='PaperInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('authorname_1', models.CharField(max_length=20)),
                ('authorname_2', models.CharField(max_length=20, null=True)),
                ('authorname_3', models.CharField(max_length=20, null=True)),
                ('authorname_4', models.CharField(max_length=20, null=True)),
                ('authorname_5', models.CharField(max_length=20, null=True)),
                ('abstract', models.TextField()),
                ('research', models.CharField(max_length=100)),
                ('paperfile', models.FileField(upload_to='paper')),
                ('state', models.CharField(default='审稿中', max_length=20)),
                ('authorID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reviewsite.usersinfo')),
            ],
        ),
        migrations.CreateModel(
            name='ExpertReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=20)),
                ('opinion', models.TextField()),
                ('expertID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reviewsite.usersinfo')),
                ('paperID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reviewsite.paperinfo')),
            ],
        ),
        migrations.CreateModel(
            name='EditorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=20)),
                ('opinion', models.TextField()),
                ('paperID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reviewsite.paperinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Allocate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExpertID_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='expert1_ID', to='reviewsite.usersinfo')),
                ('ExpertID_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='expert2_ID', to='reviewsite.usersinfo')),
                ('ExpertID_3', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='expert3_ID', to='reviewsite.usersinfo')),
                ('PaperID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reviewsite.paperinfo')),
            ],
        ),
    ]
