# Generated by Django 4.0.5 on 2022-06-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewsite', '0002_auto_20220616_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocate',
            name='ExpertID_1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='allocate',
            name='ExpertID_2',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='allocate',
            name='ExpertID_3',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='allocate',
            name='PaperID',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='editorreview',
            name='paperID',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='expertreview',
            name='expertID',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='expertreview',
            name='paperID',
            field=models.CharField(max_length=20),
        ),
    ]
